name: Application CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_ID: citric-shine-378115 # GCP project ID
  GAR_LOCATION: us-central1       # GCP Artifact Registry region
  REPOSITORY: demo-app            # GCP Artifact Registry docker repository naame
  IMAGE_NAME: demo-app                 # Docker image name

jobs:
  build:
    name: App CI/CD
    runs-on: ubuntu-latest
    # Need below permission for https://github.com/google-github-actions/auth#usage
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: '17'
          cache: 'maven'

      - name: Authenticate gcloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/234610246542/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: github-action-sa@citric-shine-378115.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build with Maven
        run: mvn clean install
        
      - name: Run Tests with Maven
        run: mvn test

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
             ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ steps.get-tag.outputs.short_ref }}
             ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            "JAR_FILE=app-springboot-ci-cd/target/spring-boot-web.jar"
