name: Application CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: App CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install
        
      - name: Run Tests with Maven
        run: mvn test